name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies for Ubuntu
      run: test "`uname -s`" = "Linux" -a -f /usr/bin/apt && sudo apt install libicu-dev convmv || true
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
